<template>
  <section id="contact" class="contact-section"><div class="section-content internal-scroll"><div class="container">
    <h2 class="section-title anim-stagger">{{ locale === 'fa' ? 'در تماس باشیم' : 'Get in Touch' }}</h2><p class="section-subtitle anim-stagger">{{ locale === 'fa' ? 'برای پروژه‌های جدید، طراحی سایت یا همکاری خوشحال می‌شوم با من در ارتباط باشید.' : 'I am always open to discussing new projects or partnership opportunities.' }}</p>
    <div class="contact-wrapper anim-stagger"><form class="contact-form" @submit.prevent="handleSubmit"><div class="form-group"><input id="name" v-model="form.name" required placeholder=" "><label for="name">{{ locale === 'fa' ? 'نام شما' : 'Your Name' }}</label></div><div class="form-group"><input id="email" v-model="form.email" type="email" required placeholder=" "><label for="email">{{ locale === 'fa' ? 'ایمیل شما' : 'Your Email' }}</label></div><div class="form-group"><textarea id="message" v-model="form.message" rows="5" required placeholder=" "></textarea><label for="message">{{ locale === 'fa' ? 'پیام شما' : 'Your Message' }}</label></div><button class="submit-button">{{ locale === 'fa' ? 'ارسال پیام' : 'Send Message' }}</button></form><div class="contact-info"><div><h3>Email</h3><a href="mailto:hoseni.erfan85@gmail.com">hoseni.erfan85@gmail.com</a></div><div><h3>{{ locale === 'fa' ? 'شبکه‌های اجتماعی' : 'Connect' }}</h3><div class="social-links"><a href="https://www.linkedin.com/in/erfan-fadakar-207a03320" target="_blank">LinkedIn</a><a href="https://github.com/Fadakari" target="_blank">GitHub</a></div></div><div><h3>{{ locale === 'fa' ? 'شماره تماس' : 'Phone' }}</h3><a href="tel:+989910689541">+98 991 068 9541</a></div></div></div>
  </div></div></section>
</template>
<script setup lang="ts">
const { locale } = useLocale(); const form=reactive({name:'',email:'',message:''}); const handleSubmit=()=>{alert(locale.value==='fa'?'پیام شما ثبت شد. به‌زودی با شما تماس می‌گیرم.':'Thank you for your message! I will get back to you soon.');Object.assign(form,{name:'',email:'',message:''})}
</script>
<style scoped>
.section-content{width:100%;height:100vh;box-sizing:border-box;overflow-y:auto;padding:8rem 2rem}.section-content::-webkit-scrollbar{display:none}.section-content{-ms-overflow-style:none;scrollbar-width:none}.container{max-width:1000px;width:100%;text-align:center;margin:auto}.section-title{font-size:2.8rem;color:#fff;margin-bottom:1rem}.section-subtitle{font-size:1.1rem;color:#e4e4e7;max-width:600px;margin:0 auto 3rem}.contact-wrapper{display:grid;grid-template-columns:2fr 1fr;gap:3rem;background:rgba(30,41,59,.95);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:3rem;text-align:left}.contact-form{display:flex;flex-direction:column}.form-group{position:relative;margin-bottom:2rem}.form-group input,.form-group textarea{width:100%;box-sizing:border-box;background:transparent;border:none;border-bottom:1px solid rgba(255,255,255,.3);color:#fff;padding:.75rem 0;font-size:1rem;outline:none}.form-group label{position:absolute;top:.75rem;left:0;color:rgba(255,255,255,.55);pointer-events:none;transition:.3s}.form-group input:focus+label,.form-group input:not(:placeholder-shown)+label,.form-group textarea:focus+label,.form-group textarea:not(:placeholder-shown)+label{top:-1rem;font-size:.8rem;color:#7dd3fc}.submit-button{background:#38bdf8;color:#020617;border:0;padding:.8rem 1.5rem;border-radius:8px;font-weight:700;cursor:pointer}.contact-info{display:flex;flex-direction:column;gap:2rem;padding-left:2rem;border-left:1px solid rgba(255,255,255,.2)}.contact-info h3{color:#7dd3fc;font-size:1rem}.contact-info a{color:#fff;text-decoration:none}.social-links{display:flex;gap:1rem}.social-links a{color:#e4e4e7}@media(max-width:992px){.contact-wrapper{grid-template-columns:1fr;padding:2rem}.contact-info{border-left:0;padding-left:0;border-top:1px solid rgba(255,255,255,.2);padding-top:2rem}}
</style>
