<template>
  <section id="projects" class="projects-section"><div class="section-content internal-scroll"><div class="container">
    <h2 class="section-title anim-stagger">{{ locale === 'fa' ? 'پروژه‌های منتخب' : 'Featured Projects' }}</h2>
    <div class="projects-grid"><article v-for="project in projects" :key="project.title" class="project-card anim-stagger"><div class="card-image-container"><img :src="project.image" :alt="project.title" class="card-image"></div><div class="card-content"><h3 class="card-title">{{ project.title }}</h3><p class="card-description">{{ project.description }}</p><div class="card-tags"><span v-for="tag in project.tags" :key="tag" class="tag">{{ tag }}</span></div><div class="card-footer"><a :href="project.liveUrl" target="_blank" rel="noopener noreferrer" class="card-button primary">Live Demo</a><a :href="project.githubUrl" target="_blank" rel="noopener noreferrer" class="card-button secondary">GitHub</a></div></div></article></div>
  </div></div></section>
</template>
<script setup lang="ts">
const { locale } = useLocale()
const projects = computed(() => locale.value === 'fa' ? [
{title:'پلتفرم استوک',description:'توسعه پلتفرم و اپلیکیشن استوک برای خرید و فروش کالا.',image:'https://raw.githubusercontent.com/Fadakari/Vue-js-portfolio/main/src/assets/image.png',tags:['HTML5','CSS3','JavaScript','Python/Flask','Kotlin'],liveUrl:'https://stockdivar.ir',githubUrl:'https://github.com/Fadakari/stock_app'},
{title:'سایت معرفی شخصی',description:'وب‌سایت Personal Branding با Nuxt و GSAP با تمرکز بر عملکرد و تجربه کاربری.',image:'https://raw.githubusercontent.com/Fadakari/Vue-js-portfolio/main/src/assets/Screenshot%202025-12-01%20125428.jpg',tags:['Vue.js','Tailwind CSS','TypeScript','Nuxt','GSAP'],liveUrl:'https://behzadheydari.ir/',githubUrl:'https://github.com/Fadakari/bio-site'}
] : [
{title:'Stock Platform',description:'Development of a platform and application for buying and selling goods.',image:'https://raw.githubusercontent.com/Fadakari/Vue-js-portfolio/main/src/assets/image.png',tags:['HTML5','CSS3','JavaScript','Python/Flask','Kotlin'],liveUrl:'https://stockdivar.ir',githubUrl:'https://github.com/Fadakari/stock_app'},
{title:'Personal Branding Site',description:'A high-performance personal branding website built with Nuxt and GSAP.',image:'https://raw.githubusercontent.com/Fadakari/Vue-js-portfolio/main/src/assets/Screenshot%202025-12-01%20125428.jpg',tags:['Vue.js','Tailwind CSS','TypeScript','Nuxt','GSAP'],liveUrl:'https://behzadheydari.ir/',githubUrl:'https://github.com/Fadakari/bio-site'}
])
</script>
<style scoped>
.section-content{height:100%;width:100%;overflow-y:auto;padding:6rem 2rem 8rem;box-sizing:border-box}.section-content::-webkit-scrollbar{display:none}.section-content{-ms-overflow-style:none;scrollbar-width:none}.container{max-width:1200px;margin:0 auto;text-align:center}.section-title{font-size:2.5rem;color:#fff;margin-bottom:3rem}.projects-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:2rem}.project-card{background:rgba(30,41,59,.95);border:1px solid rgba(255,255,255,.1);border-radius:16px;overflow:hidden;display:flex;flex-direction:column;text-align:left;transition:.3s}.project-card:hover{transform:translateY(-10px);box-shadow:0 20px 30px rgba(0,0,0,.3)}.card-image-container{width:100%;height:260px;overflow:hidden}.card-image{width:100%;height:100%;object-fit:cover;transition:.4s}.project-card:hover .card-image{transform:scale(1.05)}.card-content{padding:1.5rem;display:flex;flex-direction:column;flex-grow:1}.card-title{font-size:1.5rem;color:#fff;margin-bottom:.5rem}.card-description{color:#e4e4e7;line-height:1.7;margin-bottom:1rem}.tag{display:inline-block;background:rgba(56,189,248,.1);color:#7dd3fc;padding:.25rem .75rem;border-radius:99px;font-size:.8rem;margin-right:.5rem;margin-bottom:.5rem}.card-footer{margin-top:auto;display:flex;gap:1rem}.card-button{padding:.6rem 1.2rem;border-radius:8px;text-decoration:none;font-weight:600}.primary{background:#38bdf8;color:#020617}.secondary{color:#fff;border:1px solid #475569}@media(max-width:700px){.projects-grid{grid-template-columns:1fr}}
</style>
